### ISSUE TITLE
Links and avatars

### ISSUE THREAD

**Issue by adamavenir** [code-423n4/website#5]
We want to add competitors' links and avatars to the website.

If you're participating in the Slingshot Finance contest, drop a comment here with your:

- handle / name 
- preferred avatar
- link

Thanks! 🌈

*NOTE*: If you've already added an avatar and are participating in a new contest, just drop a comment.

**Comment by Austin-Williams** [comment]
- handle/name: @onewayfunction (Austin Williams)
- avatar: https://twitter.com/onewayfunction/photo
- link: https://twitter.com/onewayfunction

**Comment by ncitron** [comment]
- handle/name: @NoahCitron (Noah Citron)
- avatar: https://twitter.com/NoahCitron/photo
- link: https://twitter.com/NoahCitron

**Comment by gpersoon** [comment]
- handle / name: @gpersoon (Gerard Persoon)
- avatar: https://twitter.com/gpersoon/photo
- link: https://twitter.com/gpersoon

**Comment by janbro** [comment]
- handle/name: @janbro (Alejandro Munoz)
- avatar: https://twitter.com/unsafe_call/photo
- link: https://twitter.com/unsafe_call

**Comment by nedodn** [comment]
handle/name: @ndeanoden (Nate Dean Oden)
avatar: https://twitter.com/ndeanoden/photo
link: https://twitter.com/ndeanoden

**Comment by pauliax** [comment]
handle: paulius.eth
avatar: https://twitter.com/SolidityDev/photo
link: https://twitter.com/SolidityDev

**Comment by SaladStar** [comment]
handle: @ErikSal1217 (Erik Salazar)
avatar: https://twitter.com/eriksal1217/photo
link: https://twitter.com/eriksal1217

**Comment by MrToph** [comment]
handle/name: cmichel (Christoph Michel)
avatar: https://twitter.com/cmichelio/photo
link: https://twitter.com/cmichelio

**Comment by rajeevgopalakrishna** [comment]
handle/name: 0xRajeev
avatar: https://twitter.com/0xRajeev/photo
link: https://twitter.com/0xRajeev

**Comment by MrToph** [comment]
I'm in for this round, too.

**Comment by gpersoon** [comment]
i'm also doing this round

**Comment by smonicas** [comment]
handle/name: s1m0
avatar: https://twitter.com/_smonica_/photo
link: https://twitter.com/_smonica_

**Comment by toastedsteaksandwich** [comment]
handle/name: toastedsteaksandwich (Ashiq Amien)
avatar: https://twitter.com/AshiqAmien/photo
link: https://twitter.com/AshiqAmien
